# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    # Location of Julia projects
    directories:
      - "/"
      - "/docs"
      - "/lib/XSPECModels"
      - "/lib/XSPECModels/test"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore package itself
      - dependency-name: "SpectralFitting"
      - dependency-name: "XSPECModels"
    groups:
      julia-patch-updates:
        update-types: ["patch"]
